export default {
  projects: null,
  tasks:[],
  token: localStorage.getItem('access_token') || null,
  user: null,
  user_name: null,
  user_auth: null,
  departments: null,
  project_name:null,
  project_deadline:null,
  project_department:null,
  employees:null,
  subtasks:null,
  currentEmployee:null,
  employee_page:null,
  authorisations:null,
  filtered_employees:null,
}
